name: CI/CD Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm install  # Usando install em vez de ci para evitar erro de lock file
      
      - name: Run tests
        run: npm test

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t hello-world-app .
        
      - name: Test container
        run: |
          docker run --name test-app -d -p 3000:3000 hello-world-app
          sleep 5
          curl -s http://localhost:3000 | grep "Hello World" || (docker logs test-app && exit 1)
          docker stop test-app
          docker rm test-app
