name: CI Pipeline with Docker

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
          
      - name: Run unit tests
        run: npx jest --ci --verbose

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: docker build -t hello-world-app .
        
      - name: Run container tests
        run: |
          docker run --name test-app -d -p 3000:3000 hello-world-app
          sleep 5 # Wait for app to start
          curl -s http://localhost:3000 | grep "Hello World"
          docker stop test-app
          docker rm test-app
